package org.cenicana.bio.cli;

import org.cenicana.bio.core.ComparativeGenomicsAnalyzer;
import picocli.CommandLine.Command;
import picocli.CommandLine.Option;

import java.util.concurrent.Callable;

/**
 * Command for Comparative Genomics analysis.
 */
@Command(name = "comp-gen", 
         mixinStandardHelpOptions = true, 
         description = "Integrate and visualize Comparative Genomics results (McScanX/Synmap2) with functional annotations.")
public class ComparativeGenomicsCommand implements Callable<Integer> {

    @Option(names = {"--gff1"}, required = true, description = "GFF file for Genome 1. Usually the simplified 4-column GFF used as input for McScanX (Chr, ID, Start, End) or a standard GFF3.")
    private String gff1;

    @Option(names = {"--gff2"}, required = true, description = "GFF file for Genome 2. Usually the simplified 4-column GFF used as input for McScanX (Chr, ID, Start, End) or a standard GFF3.")
    private String gff2;

    @Option(names = {"--collinearity"}, required = true, description = "The .collinearity output file generated by McScanX containing the syntenic blocks and gene pairs.")
    private String collinearity;

    @Option(names = {"--cds1"}, description = "[Optional] CDS FASTA file for Genome 1. Used to extract sequence lengths for the TSV report.")
    private String cds1;

    @Option(names = {"--cds2"}, description = "[Optional] CDS FASTA file for Genome 2. Used to extract sequence lengths for the TSV report.")
    private String cds2;

    @Option(names = {"--prot1"}, description = "[Optional] Protein FASTA file for Genome 1. Used to extract protein lengths for the TSV report.")
    private String prot1;

    @Option(names = {"--prot2"}, description = "[Optional] Protein FASTA file for Genome 2. Used to extract protein lengths for the TSV report.")
    private String prot2;

    @Option(names = {"-o", "--output"}, description = "Path for the output integrated TSV report.", defaultValue = "comp_gen_report.tsv")
    private String output;

    @Option(names = {"--viz"}, description = "Path for the output interactive HTML visualization (Advanced Synteny Explorer).")
    private String vizOutput;

    @Option(names = {"--annot1"}, description = "[Optional] Functional annotation file for Genome 1. Can be a standard GFF3 (extracts from column 9 attributes like 'description' or 'Note') or a TSV file (GeneID \\t Description). Derived from tools like MAKER, Helixer, or Blast2GO.")
    private String annot1;

    @Option(names = {"--annot2"}, description = "[Optional] Functional annotation file for Genome 2. Can be a standard GFF3 (extracts from column 9 attributes like 'description' or 'Note') or a TSV file (GeneID \\t Description). Derived from tools like MAKER, Helixer, or Blast2GO.")
    private String annot2;

    @Option(names = {"--vcf"}, description = "[Optional] VCF file mapped to Genome 2 (e.g., CC-01-1940) to calculate population diversity (SNP density) per syntenic block and generate an Evolutionary Heatmap.")
    private String vcf;

    @Option(names = {"--kaks"}, description = "[Optional] Ka/Ks result file (TSV: Gene1 \\t Gene2 \\t Ka \\t Ks \\t Ka/Ks). Used to visualize evolutionary selection pressure.")
    private String kaks;

    @Override
    public Integer call() throws Exception {
        ComparativeGenomicsAnalyzer analyzer = new ComparativeGenomicsAnalyzer();
        analyzer.runAnalysis(gff1, gff2, collinearity, cds1, cds2, prot1, prot2, output, vizOutput, annot1, annot2, vcf, kaks);
        return 0;
    }
}
