package org.cenicana.bio.cli;

import org.cenicana.bio.core.JoinMapCpFormat;
import picocli.CommandLine.Command;
import picocli.CommandLine.Parameters;
import java.util.concurrent.Callable;

@Command(name = "joinmap", aliases = { "20" }, description = "Converts and fixes JoinMap CP format files.")
public class JoinMapCommand implements Callable<Integer> {

    @Parameters(index = "0", description = "The JoinMap format file generated by tools like NGSEP.")
    private String joinmapFile;

    @Override
    public Integer call() throws Exception {
        System.out.println("[JoinMap] Processing file: " + joinmapFile);
        JoinMapCpFormat joinmap = new JoinMapCpFormat();
        joinmap.fixformat(joinmapFile);
        System.out.println("[JoinMap] Done.");
        return 0;
    }
}
